//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeMayShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyXeMayEntities : DbContext
    {
        public QuanLyXeMayEntities()
            : base("name=QuanLyXeMayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual DbSet<ChiTietPhieuXuat> ChiTietPhieuXuats { get; set; }
        public virtual DbSet<DongXe> DongXes { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiXe> LoaiXes { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<PhieuXuat> PhieuXuats { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
    
        public virtual ObjectResult<Admin> sp_CheckLogin(string tenDangNhap, string matKhau)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Admin>("sp_CheckLogin", tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<Admin> sp_CheckLogin(string tenDangNhap, string matKhau, MergeOption mergeOption)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Admin>("sp_CheckLogin", mergeOption, tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<KhachHang> sp_CheckLoginKhachHang(string tenDangNhap, string matKhau)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang>("sp_CheckLoginKhachHang", tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<KhachHang> sp_CheckLoginKhachHang(string tenDangNhap, string matKhau, MergeOption mergeOption)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang>("sp_CheckLoginKhachHang", mergeOption, tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual int sp_DangKyKhachHang(string tenKhachHang, string diaChi, string dienThoai, string tenDangNhap, string matKhau)
        {
            var tenKhachHangParameter = tenKhachHang != null ?
                new ObjectParameter("TenKhachHang", tenKhachHang) :
                new ObjectParameter("TenKhachHang", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DangKyKhachHang", tenKhachHangParameter, diaChiParameter, dienThoaiParameter, tenDangNhapParameter, matKhauParameter);
        }
    
        [DbFunction("QuanLyXeMayEntities", "LayKhachHang")]
        public virtual IQueryable<KhachHang> LayKhachHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<KhachHang>("[QuanLyXeMayEntities].[LayKhachHang]()");
        }
    
        public virtual ObjectResult<KhachHang> sp_TimKiemKhachHangTheoMaKhachHang(Nullable<int> makhachhang)
        {
            var makhachhangParameter = makhachhang.HasValue ?
                new ObjectParameter("makhachhang", makhachhang) :
                new ObjectParameter("makhachhang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang>("sp_TimKiemKhachHangTheoMaKhachHang", makhachhangParameter);
        }
    
        public virtual ObjectResult<KhachHang> sp_TimKiemKhachHangTheoMaKhachHang(Nullable<int> makhachhang, MergeOption mergeOption)
        {
            var makhachhangParameter = makhachhang.HasValue ?
                new ObjectParameter("makhachhang", makhachhang) :
                new ObjectParameter("makhachhang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang>("sp_TimKiemKhachHangTheoMaKhachHang", mergeOption, makhachhangParameter);
        }
    
        [DbFunction("QuanLyXeMayEntities", "ft_TimKiemKhachHangTheoMaKhachHang")]
        public virtual IQueryable<ft_TimKiemKhachHangTheoMaKhachHang_Result> ft_TimKiemKhachHangTheoMaKhachHang(Nullable<int> makhachhang)
        {
            var makhachhangParameter = makhachhang.HasValue ?
                new ObjectParameter("makhachhang", makhachhang) :
                new ObjectParameter("makhachhang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_TimKiemKhachHangTheoMaKhachHang_Result>("[QuanLyXeMayEntities].[ft_TimKiemKhachHangTheoMaKhachHang](@makhachhang)", makhachhangParameter);
        }
    
        [DbFunction("QuanLyXeMayEntities", "ft_TimKiemThongTinXe")]
        public virtual IQueryable<ft_TimKiemThongTinXe_Result> ft_TimKiemThongTinXe(Nullable<int> intValue, string stringValue)
        {
            var intValueParameter = intValue.HasValue ?
                new ObjectParameter("IntValue", intValue) :
                new ObjectParameter("IntValue", typeof(int));
    
            var stringValueParameter = stringValue != null ?
                new ObjectParameter("StringValue", stringValue) :
                new ObjectParameter("StringValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_TimKiemThongTinXe_Result>("[QuanLyXeMayEntities].[ft_TimKiemThongTinXe](@IntValue, @StringValue)", intValueParameter, stringValueParameter);
        }
    
        public virtual int sp_CapNhatThongTinKhachHang(Nullable<int> maKhachHang, string tenKhachHang, string diaChi, string dienThoai, string tenDangNhap, string matKhau)
        {
            var maKhachHangParameter = maKhachHang.HasValue ?
                new ObjectParameter("MaKhachHang", maKhachHang) :
                new ObjectParameter("MaKhachHang", typeof(int));
    
            var tenKhachHangParameter = tenKhachHang != null ?
                new ObjectParameter("TenKhachHang", tenKhachHang) :
                new ObjectParameter("TenKhachHang", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatThongTinKhachHang", maKhachHangParameter, tenKhachHangParameter, diaChiParameter, dienThoaiParameter, tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual int sp_ThemXe(Nullable<int> maloaixe, Nullable<int> madongxe, string tenxe, string motaxe, string thongtinbaohanh, Nullable<double> dongiaxe)
        {
            var maloaixeParameter = maloaixe.HasValue ?
                new ObjectParameter("maloaixe", maloaixe) :
                new ObjectParameter("maloaixe", typeof(int));
    
            var madongxeParameter = madongxe.HasValue ?
                new ObjectParameter("madongxe", madongxe) :
                new ObjectParameter("madongxe", typeof(int));
    
            var tenxeParameter = tenxe != null ?
                new ObjectParameter("tenxe", tenxe) :
                new ObjectParameter("tenxe", typeof(string));
    
            var motaxeParameter = motaxe != null ?
                new ObjectParameter("motaxe", motaxe) :
                new ObjectParameter("motaxe", typeof(string));
    
            var thongtinbaohanhParameter = thongtinbaohanh != null ?
                new ObjectParameter("thongtinbaohanh", thongtinbaohanh) :
                new ObjectParameter("thongtinbaohanh", typeof(string));
    
            var dongiaxeParameter = dongiaxe.HasValue ?
                new ObjectParameter("dongiaxe", dongiaxe) :
                new ObjectParameter("dongiaxe", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemXe", maloaixeParameter, madongxeParameter, tenxeParameter, motaxeParameter, thongtinbaohanhParameter, dongiaxeParameter);
        }
    
        public virtual int sp_XoaXe(Nullable<int> maxe)
        {
            var maxeParameter = maxe.HasValue ?
                new ObjectParameter("maxe", maxe) :
                new ObjectParameter("maxe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaXe", maxeParameter);
        }
    
        public virtual ObjectResult<KhachHang> sp_TimKiemKhachHang(string value, Nullable<int> makhachhang)
        {
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var makhachhangParameter = makhachhang.HasValue ?
                new ObjectParameter("makhachhang", makhachhang) :
                new ObjectParameter("makhachhang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang>("sp_TimKiemKhachHang", valueParameter, makhachhangParameter);
        }
    
        public virtual ObjectResult<KhachHang> sp_TimKiemKhachHang(string value, Nullable<int> makhachhang, MergeOption mergeOption)
        {
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var makhachhangParameter = makhachhang.HasValue ?
                new ObjectParameter("makhachhang", makhachhang) :
                new ObjectParameter("makhachhang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang>("sp_TimKiemKhachHang", mergeOption, valueParameter, makhachhangParameter);
        }
    }
}
