//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeMayShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyXeMayEntities : DbContext
    {
        public QuanLyXeMayEntities()
            : base("name=QuanLyXeMayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<ChiNhanh> ChiNhanhs { get; set; }
        public virtual DbSet<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual DbSet<DongXe> DongXes { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiXe> LoaiXes { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuBaoHanh> PhieuBaoHanhs { get; set; }
        public virtual DbSet<PhieuDatXe> PhieuDatXes { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<PhieuXuat> PhieuXuats { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
    
        public virtual int sp_TaoChiNhanh(string tenChiNhanh, string diaChi)
        {
            var tenChiNhanhParameter = tenChiNhanh != null ?
                new ObjectParameter("TenChiNhanh", tenChiNhanh) :
                new ObjectParameter("TenChiNhanh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoChiNhanh", tenChiNhanhParameter, diaChiParameter);
        }
    
        public virtual int sp_TaoChiTietPhieuNhap(Nullable<int> maXe, Nullable<int> maPhieuNhap, Nullable<int> soLuongNhap, Nullable<double> donGiaNhap)
        {
            var maXeParameter = maXe.HasValue ?
                new ObjectParameter("MaXe", maXe) :
                new ObjectParameter("MaXe", typeof(int));
    
            var maPhieuNhapParameter = maPhieuNhap.HasValue ?
                new ObjectParameter("MaPhieuNhap", maPhieuNhap) :
                new ObjectParameter("MaPhieuNhap", typeof(int));
    
            var soLuongNhapParameter = soLuongNhap.HasValue ?
                new ObjectParameter("SoLuongNhap", soLuongNhap) :
                new ObjectParameter("SoLuongNhap", typeof(int));
    
            var donGiaNhapParameter = donGiaNhap.HasValue ?
                new ObjectParameter("DonGiaNhap", donGiaNhap) :
                new ObjectParameter("DonGiaNhap", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoChiTietPhieuNhap", maXeParameter, maPhieuNhapParameter, soLuongNhapParameter, donGiaNhapParameter);
        }
    
        public virtual int sp_TaoNhaCungCap(string tenNhaCungCap, string diaChi, string dienThoai, string email)
        {
            var tenNhaCungCapParameter = tenNhaCungCap != null ?
                new ObjectParameter("TenNhaCungCap", tenNhaCungCap) :
                new ObjectParameter("TenNhaCungCap", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoNhaCungCap", tenNhaCungCapParameter, diaChiParameter, dienThoaiParameter, emailParameter);
        }
    
        public virtual int sp_TaoPhieuNhapMoi(Nullable<int> maNhanVien, Nullable<int> maNhaCungCap, Nullable<int> maChiNhanh)
        {
            var maNhanVienParameter = maNhanVien.HasValue ?
                new ObjectParameter("MaNhanVien", maNhanVien) :
                new ObjectParameter("MaNhanVien", typeof(int));
    
            var maNhaCungCapParameter = maNhaCungCap.HasValue ?
                new ObjectParameter("MaNhaCungCap", maNhaCungCap) :
                new ObjectParameter("MaNhaCungCap", typeof(int));
    
            var maChiNhanhParameter = maChiNhanh.HasValue ?
                new ObjectParameter("MaChiNhanh", maChiNhanh) :
                new ObjectParameter("MaChiNhanh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoPhieuNhapMoi", maNhanVienParameter, maNhaCungCapParameter, maChiNhanhParameter);
        }
    
        public virtual int sp_ThemNhanVien(string tenNhanVien, string namSinh, string gioiTinh, string diaChi, string dienThoai, Nullable<int> maChiNhanh)
        {
            var tenNhanVienParameter = tenNhanVien != null ?
                new ObjectParameter("TenNhanVien", tenNhanVien) :
                new ObjectParameter("TenNhanVien", typeof(string));
    
            var namSinhParameter = namSinh != null ?
                new ObjectParameter("NamSinh", namSinh) :
                new ObjectParameter("NamSinh", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var maChiNhanhParameter = maChiNhanh.HasValue ?
                new ObjectParameter("MaChiNhanh", maChiNhanh) :
                new ObjectParameter("MaChiNhanh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNhanVien", tenNhanVienParameter, namSinhParameter, gioiTinhParameter, diaChiParameter, dienThoaiParameter, maChiNhanhParameter);
        }
    
        public virtual ObjectResult<KhachHang> sp_TimKiemKhachHang(string dienthoai, string tenKH)
        {
            var dienthoaiParameter = dienthoai != null ?
                new ObjectParameter("dienthoai", dienthoai) :
                new ObjectParameter("dienthoai", typeof(string));
    
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang>("sp_TimKiemKhachHang", dienthoaiParameter, tenKHParameter);
        }
    
        public virtual ObjectResult<KhachHang> sp_TimKiemKhachHang(string dienthoai, string tenKH, MergeOption mergeOption)
        {
            var dienthoaiParameter = dienthoai != null ?
                new ObjectParameter("dienthoai", dienthoai) :
                new ObjectParameter("dienthoai", typeof(string));
    
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang>("sp_TimKiemKhachHang", mergeOption, dienthoaiParameter, tenKHParameter);
        }
    
        public virtual ObjectResult<KhachHang> sp_XuatTatCaKhachHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang>("sp_XuatTatCaKhachHang");
        }
    
        public virtual ObjectResult<KhachHang> sp_XuatTatCaKhachHang(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang>("sp_XuatTatCaKhachHang", mergeOption);
        }
    
        public virtual int sp_TaoPhieuDatXe(Nullable<int> maXe, string tenNguoiDat, string sDT)
        {
            var maXeParameter = maXe.HasValue ?
                new ObjectParameter("MaXe", maXe) :
                new ObjectParameter("MaXe", typeof(int));
    
            var tenNguoiDatParameter = tenNguoiDat != null ?
                new ObjectParameter("TenNguoiDat", tenNguoiDat) :
                new ObjectParameter("TenNguoiDat", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoPhieuDatXe", maXeParameter, tenNguoiDatParameter, sDTParameter);
        }
    
        public virtual ObjectResult<Xe> sp_TimKiemXe(string value, Nullable<int> ma)
        {
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var maParameter = ma.HasValue ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Xe>("sp_TimKiemXe", valueParameter, maParameter);
        }
    
        public virtual ObjectResult<Xe> sp_TimKiemXe(string value, Nullable<int> ma, MergeOption mergeOption)
        {
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var maParameter = ma.HasValue ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Xe>("sp_TimKiemXe", mergeOption, valueParameter, maParameter);
        }
    
        public virtual ObjectResult<Admin> sp_CheckLogin(string tenDangNhap, string matKhau)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Admin>("sp_CheckLogin", tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<Admin> sp_CheckLogin(string tenDangNhap, string matKhau, MergeOption mergeOption)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Admin>("sp_CheckLogin", mergeOption, tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual int sp_TaoPhieuXuat(Nullable<int> maNhanVien, Nullable<int> maKhachHanh, Nullable<int> maChiNhanh, Nullable<int> maXe, Nullable<int> thanhTienXuat)
        {
            var maNhanVienParameter = maNhanVien.HasValue ?
                new ObjectParameter("MaNhanVien", maNhanVien) :
                new ObjectParameter("MaNhanVien", typeof(int));
    
            var maKhachHanhParameter = maKhachHanh.HasValue ?
                new ObjectParameter("MaKhachHanh", maKhachHanh) :
                new ObjectParameter("MaKhachHanh", typeof(int));
    
            var maChiNhanhParameter = maChiNhanh.HasValue ?
                new ObjectParameter("MaChiNhanh", maChiNhanh) :
                new ObjectParameter("MaChiNhanh", typeof(int));
    
            var maXeParameter = maXe.HasValue ?
                new ObjectParameter("MaXe", maXe) :
                new ObjectParameter("MaXe", typeof(int));
    
            var thanhTienXuatParameter = thanhTienXuat.HasValue ?
                new ObjectParameter("ThanhTienXuat", thanhTienXuat) :
                new ObjectParameter("ThanhTienXuat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoPhieuXuat", maNhanVienParameter, maKhachHanhParameter, maChiNhanhParameter, maXeParameter, thanhTienXuatParameter);
        }
    
        public virtual int sp_CapNhatThongTinChiNhanh(Nullable<int> maChiNhanh, string tenChiNhanh, string diaChi)
        {
            var maChiNhanhParameter = maChiNhanh.HasValue ?
                new ObjectParameter("MaChiNhanh", maChiNhanh) :
                new ObjectParameter("MaChiNhanh", typeof(int));
    
            var tenChiNhanhParameter = tenChiNhanh != null ?
                new ObjectParameter("TenChiNhanh", tenChiNhanh) :
                new ObjectParameter("TenChiNhanh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatThongTinChiNhanh", maChiNhanhParameter, tenChiNhanhParameter, diaChiParameter);
        }
    
        public virtual int sp_XoaChiNhanh(Nullable<int> maChiNhanh)
        {
            var maChiNhanhParameter = maChiNhanh.HasValue ?
                new ObjectParameter("MaChiNhanh", maChiNhanh) :
                new ObjectParameter("MaChiNhanh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaChiNhanh", maChiNhanhParameter);
        }
    }
}
